[package]
name = "pkauth"
version = "0.1.0"
authors = ["James Parker <jp@pkauth.com>"]

[dependencies]
base64="*"
ring="*"
ripemd160="*"
serde="*"
untrusted="^0.6.0"
crypto-abstract={path="../rs-crypto-abstract"}
